services:
    vivait_licensing_guzzle:
        class: GuzzleHttp\Client

    vivait_licensing_client.strategy.application:
        class: Vivait\LicensingClientBundle\Strategy\ApplicationStrategy
        arguments: [@request, @vivait_licensing_guzzle, @doctrine.orm.default_entity_manager,  %vivait_licensing_client.debug%,  %vivait_licensing_client.oauth.token_url%, %vivait_licensing_client.oauth.check_url%, %vivait_licensing_client.application%, %vivait_licensing_client.client_id%, %vivait_licensing_client.client_secret%]
        public: true
        scope: request

    vivait_licensing_client.strategy.endpoint:
        class: Vivait\LicensingClientBundle\Strategy\EndpointStrategy
        arguments: [@request, @vivait_licensing_guzzle, @doctrine.orm.default_entity_manager,  %vivait_licensing_client.debug%,  %vivait_licensing_client.oauth.token_url%, %vivait_licensing_client.oauth.check_url%, %vivait_licensing_client.application%]
        public: true
        scope: request

    vivait_licensing_client.request.listener:
        class: Vivait\LicensingClientBundle\EventListener\ProtectEndpointListener
        arguments: [@annotation_reader, @vivait_licensing_client.strategy.endpoint]
        scope: request
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
